#############################################################################
# Configuration information for using the mouse genome in the mapping simulation pipeline
#############################################################################

data_dir: /n/holylfs05/LABS/informatics/Users/gthomas/Mapping-simulations-data/
# The base datadir where reference genomes and output data are stored

ref_str: mm39
# The subfolder and abbreviation for the current reference genome

ref_file: Mus_musculus.GRCm39.dna.primary_assembly.chromes.fa
# The current reference genome directory
# Must be pre-indexed with:
# 1. samtools faidx
# 2. bwa index
# 3. picard CreateSequenceDictionary

# Full reference path should be:
# <data_dir>/<ref_str>/<ref_file>

regions: ["18", "19"]
# The regions in the reference genome to simulate reads over. Will be
# extracted with samtools faidx

covs: ["20", "30"]
# The varying amounts of coverage to simulate

divs: ["0.02", "0.04"]
# The varying amounts of divergence to simulate